name: Build Native Binaries

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21' # Используем стабильную 21 GraalVM
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Build Native Image
        run: ./gradlew :app:nativeCompile --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ws-mdns-proxy-${{ matrix.os }}
          path: |
            app/build/native/nativeCompile/ws-mdns-proxy
            app/build/native/nativeCompile/ws-mdns-proxy.exe
